/**
 * Bundles the game into a single Apps Script file. Run: node google/build.js
 *
 * Output: google/INSTALL.gs — collector.gs plus the whole game inlined as one
 * base64 string. Base64 rather than a template literal so nothing in the game
 * source (backticks, ${…}, backslashes) can break the generated file.
 */
const fs = require("fs"), path = require("path");
const GAME = path.join(__dirname, "..", "high-low-casino");
const read = f => fs.readFileSync(path.join(GAME, f), "utf8");

let html = read("index.html");

// Inline every stylesheet and script the page links to.
html = html.replace(/<link rel="stylesheet" href="([^"]+)">/g,
  (_, f) => "<style>\n" + read(f) + "\n</style>");
html = html.replace(/<script src="([^"]+)"><\/script>/g,
  (_, f) => "<script>\n" + read(f) + "\n</script>");

// Dropped for the Apps Script build: the manifest and icon are separate files
// that HtmlService does not serve, and the service worker cannot register in
// its sandboxed iframe (the game already tolerates that failing).
html = html.replace(/<link rel="manifest"[^>]*>\n?/g, "");

const left = html.match(/(?:src|href)="(?!https?:|data:)[^"]+"/g) || [];
if (left.length) {
  console.error("unresolved local references:", left.join(", "));
  process.exit(1);
}

const b64 = Buffer.from(html, "utf8").toString("base64");
const out = fs.readFileSync(path.join(__dirname, "collector.gs"), "utf8") +
  "\n/* ---- generated by google/build.js — do not edit below ---- */\n" +
  "const GAME_B64_ = '" + b64 + "';\n";

fs.writeFileSync(path.join(__dirname, "INSTALL.gs"), out);
console.log(`INSTALL.gs written — game ${(html.length / 1024).toFixed(0)} KB, ` +
            `file ${(out.length / 1024).toFixed(0)} KB`);
